# Generated by Django 6.1 on 2026-08-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('devEui', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('deviceName', models.CharField(max_length=255)),
                ('deviceProfileId', models.CharField(max_length=36)),
                ('deviceProfileName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('pk', models.CompositePrimaryKey('device', 'time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('object', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='app.device')),
            ],
        ),
    ]
